### ISSUE TITLE
javassist.CannotCompileException: [source error] syntax error near " android.os.IBinder "

### ISSUE THREAD

**Issue by dinosn** [BishopFox/rmiscout#7]
Hi, 
  I'm having the following error reported regardless the option that is selected. 

The command that created the error on this case was

rmiscout bruteforce -i lists/prototypes.txt -r void,boolean,long -p String,int -l 1,4 host 1099

Generating Permutations for [void] type...
Finished generating and querying 76500 Permutations

[ERROR] Did you forget to remove the interface name from the method name?

Full Stacktrace:

javassist.CannotCompileException: [source error] syntax error near " android.os.IBinder "
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at com.bishopfox.rmiscout.RMIConnector.generateStubs(RMIConnector.java:197)
	at com.bishopfox.rmiscout.RMIConnector.<init>(RMIConnector.java:124)
	at com.bishopfox.rmiscout.RMIScout.process(RMIScout.java:198)
	at com.bishopfox.rmiscout.RMIScout.main(RMIScout.java:158)
Caused by: compile error: syntax error near " android.os.IBinder "
	at javassist.compiler.Parser.parseField(Parser.java:91)
	at javassist.compiler.Parser.parseMember1(Parser.java:67)
	at javassist.compiler.Javac.compile(Javac.java:90)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 5 more

**Comment by the-bumble** [comment]
Hey dinosn,

Thank you for the report! The `prototypes.txt` list contains full method signatures including parameters while `methods.txt` contains a list of method names. The bruteforce subcommand takes in a list of method names (`lists/methods.txt`). 

I can see how that can be confusing and RMIScout could provide a better error message. I will be sure to add a more detailed error message in the next release. :)

Feel free to reach out if you are still encountering any issues.

Thanks again!

Jake
