### ISSUE TITLE
Error in openjdk version "11.0.7-ea" 2020-04-14

### ISSUE THREAD

**Issue by yehgdotnet** [BishopFox/rmiscout#8]
kali@kali:/opt/rmiscout$ ./rmiscout.sh bruteforce -i lists/methods.txt -r void,boolean,long -p String,int -l 1,4 [ip] [port
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Generating Permutations for [void] type...
Finished generating and querying 1110 Permutations

[ERROR] Did you forget to remove the interface name from the method name?
                                                                                              
Full Stacktrace:                                                                              
                                                                                              
javassist.CannotCompileException: by java.lang.ClassFormatError: Illegal class name "" in class file 
        at javassist.ClassPool.toClass(ClassPool.java:1120)
        at javassist.ClassPool.toClass(ClassPool.java:1063)
        at javassist.CtClass.toClass(CtClass.java:1315)
        at com.bishopfox.rmiscout.RMIConnector.generateStubs(RMIConnector.java:213)
        at com.bishopfox.rmiscout.RMIConnector.<init>(RMIConnector.java:124)
        at com.bishopfox.rmiscout.RMIScout.process(RMIScout.java:198)
        at com.bishopfox.rmiscout.RMIScout.main(RMIScout.java:158)
Caused by: java.lang.ClassFormatError: Illegal class name "" in class file 
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:878)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javassist.ClassPool.toClass2(ClassPool.java:1133)
        at javassist.ClassPool.toClass(ClassPool.java:1114)
        ... 6 more

kali@kali:/opt/rmiscout$ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "11.0.7-ea" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7-ea+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.7-ea+9-post-Debian-1, mixed mode, sharing)

**Comment by mohemiv** [comment]
The same issue with the example cmdline from README.md:
```
$ java -jar ./rmiscout-1.03-SNAPSHOT-all.jar wordlist -i lists/prototypes.txt <host> <port>

[ERROR] Did you forget to remove the interface name from the method name?

Full Stacktrace:

javassist.CannotCompileException: by java.lang.ClassFormatError: Illegal class name "" in class file 
	at javassist.ClassPool.toClass(ClassPool.java:1120)
	at javassist.ClassPool.toClass(ClassPool.java:1063)
	at javassist.CtClass.toClass(CtClass.java:1315)
	at com.bishopfox.rmiscout.RMIConnector.generateStubs(RMIConnector.java:213)
	at com.bishopfox.rmiscout.RMIConnector.<init>(RMIConnector.java:124)
	at com.bishopfox.rmiscout.RMIScout.process(RMIScout.java:198)
	at com.bishopfox.rmiscout.RMIScout.main(RMIScout.java:136)
Caused by: java.lang.ClassFormatError: Illegal class name "" in class file 
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1133)
	at javassist.ClassPool.toClass(ClassPool.java:1114)
	... 6 more
```

```
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

**Comment by the-bumble** [comment]
Hi all,

I'm having trouble reproducing this on the master branch. It may relate to a bug with registry names or ActivationStubs. I believe this will be fixed with a new major release that will be published on Tuesday 12/08/2020 (possibly sooner). Apologies for the delay.

Thank you!

Jake

**Comment by the-bumble** [comment]
Hope the new release fixed it! Feel free to reopen the issue if the issues persist.
